version: '3'
services:
  postgres:
    image: postgres:15.4-alpine
    container_name: my-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  web:
    build: .
    depends_on:
      - postgres
    entrypoint: ./docker-rails.sh
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - RAILS_ENV=${RAILS_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - HOST_NAME=${HOST_NAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - VITE_RUBY_HOST=vite
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/book-store-vue3
  vite:
    build: .
    depends_on:
      - web
    entrypoint: ./docker-vite.sh
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: ${RAILS_ENV}
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/book-store-vue3
volumes:
  postgres_data: {}
networks:
  default:
    name: book_store_vue3_default
